### ISSUE TITLE
ERROR whatBump is not a function

### ISSUE THREAD

**Issue by chrisjbrown** [hyoban/release-it-pnpm#17]
### Describe the bug

I've tried using this package with all different settings. Including what is on the documentation page.
But I always get this error.

`ERROR whatBump is not a function`

Seems like `whatBump` is a function in conventional-recommended-bump but that's about all I've been able to discern
https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump#readme

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 229.23 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.asdf/installs/nodejs/21.6.1/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/21.6.1/bin/yarn
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 9.3.0 - ~/.asdf/installs/nodejs/21.6.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hyoban** [comment]
Can you share a minimal reproduction? Thanks!

**Comment by chrisjbrown** [comment]
For anyone else who sees this error.
For me the issue was somehow related to another dependency installing `conventional-changelog-conventionalcommits` version < 8. Event though both a 7.x and an 8.x version were installed the preset loader function was always selecting the 7.x version resulting in this error. I wasn't able to recreate the issue as the reproduction I made would choose the 8.x version.

Not sure what causes one version to be selected over another. Explicitly adding `conventional-changelog-conventionalcommits@8.x` within my projects dev dependencies has resolved the issue for me.
